model: gpt-3.5-turbo-1106
# model: gpt-4-1106-preview
temperature: 0.0
num_samples: 8000 # set to 0 to label the full dataset
output_filename: taxonomy_labels
local_output_directory: outputs/labels/taxonomy
s3_directory: data/labels/child_development/
allowed_datasets:
  - taxonomy_labelling_sample # Curated sample of OpenAlex and Google Patents
