model: gpt-3.5-turbo-1106
temperature: 0.0
num_samples: 5
output_filename: taxonomy_labels
local_output_directory: outputs/labels/taxonomy
s3_directory: data/labels/
dataset: taxonomy_labelling_sample
