# Training arguments
learning_rate: 0.00002
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
gradient_accumulation_steps: 2
num_train_epochs: 30
weight_decay: 0
evaluation_strategy: "epoch"
save_strategy: "epoch"
metric_for_best_model: "f1"
load_best_model_at_end: True
early_stopping_patience: 5
report_to: "none"
seed: 42

# Type of problem for the classifier
problem_type: "single_label_classification"

# Sample size
openalex_sample_size: 500

# Sweep parameters options for method are random/grid/bayes 
# (grid is exhaustive so needs list of values, 
# random is random search so can have min/max)
sweep_config:
  method: "random"
  parameters:
    learning_rate:
      min: 0.00001
      max: 0.0001
    # num_train_epochs:
    #   values: [5, 10, 20, 30, 40, 50]
    # per_device_train_batch_size:
    #   values: [8, 16, 32, 64]
    early_stopping_patience:
      values: [3, 5, 7, 10]
