# OpenAlex starter concepts
openalex_concepts:
  - "C109260823" # child development
  - "C2993937534" # childhood development
  - "C2777082460" # early childhood
  - "C2911196330" # child rearing
  - "C2993037610" # child care
  - "C2779415726" # child protection
  - "C2781192327" # child behavior checklist
  - "C15471489" # child psychotherapy
  - "C178229462" # early childhood education
