seed: 42

# OpenAlex starter concepts
openalex_concepts:
  - "C109260823" # child development
  - "C2993937534" # childhood development
  - "C2777082460" # early childhood
  - "C2911196330" # child rearing
  - "C2993037610" # child care
  - "C2779415726" # child protection
  - "C2781192327" # child behavior checklist
  - "C15471489" # child psychotherapy
  - "C178229462" # early childhood education
openalex_years:
  - 2019
  - 2020
  - 2021
  - 2022
  - 2023
  # openalex keywords (for expanding on the seed concepts)
openalex_keywords:
  - "'artificial intelligence'"
  - "assess"
  - "assessment"
  - "'augmented reality'"
  - "autism"
  - "behaviour"
  - "development"
  - "'eye tracking'"
  - "genetics"
  - "income"
  - "learning"
  - "'learning environment'"
  - "monitor"
  - "psychotherapy"
  - "'randomised controlled trials'"
  - "robotics"
  - "'social media'"
  - "'social services'"
  - "'special need'"
  - "technology"
  - "'virtual reality'"
  - "wearable"

taxonomy:
  n_works: 20
  sheet_id: "1KIXSjS2MktbUKuyM-lprSK56kOh14u_gmHyGdHce87w"
  sheet_name: "initial_taxonomy"
patents_data_path: "data/patents/"

patents_data_version: "GooglePatents_20231106_175151"
